# Generated by Django 2.2.4 on 2019-12-02 16:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_category_name', models.CharField(max_length=50)),
                ('incident_category_slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_title', models.CharField(max_length=50)),
                ('incident_id', models.IntegerField()),
                ('incident_slug', models.SlugField()),
                ('incident_description', models.CharField(max_length=200)),
                ('incident_image', models.ImageField(upload_to='images/')),
                ('incident_severity', models.CharField(choices=[('Critical', 'C'), ('HIGH', 'H'), ('MEDIUM', 'M'), ('LOW', 'L')], max_length=10)),
                ('incident_assigned', models.CharField(max_length=40)),
                ('incident_status', models.CharField(choices=[('Open', 'O'), ('In Progress', 'I'), ('Closed', 'C')], max_length=20)),
                ('incident_date', models.DateField(default=datetime.datetime.now)),
                ('incident_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentcategory', to='incidents.IncidentCategory')),
            ],
        ),
    ]
