# Generated by Django 2.2.4 on 2019-12-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emai', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
